# Generated by Django 2.2.7 on 2019-11-28 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('aeropuerto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vuelos.Aeropuerto')),
                ('aeropuerto_salida', models.DateField(blank=True)),
                ('fecha_salida', models.DateTimeField(blank=True)),
                ('aeropuerto_llegada', models.DateField(blank=True)),
                ('fecha_llegada', models.DateTimeField(blank=True)),
                ('codigo_vuelo', models.CharField(max_length=200)),
            ],
        ),
    ]
