# Generated by Django 2.2.7 on 2019-11-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaindividualizado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='nombre_informe',
        ),
    ]
